export const staticRoutes: AppRoute.RowRoute[] = [
  // Bàn làm việc
  {
    name: "dashboard",
    path: "/dashboard",
    title: "Bàn làm việc",
    requiresAuth: true,
    icon: "icon-park-outline:database-network-point", // icon tổng quan
    menuType: "dir",
    componentPath: null,
    id: 1,
    pid: null,
  },
  {
    name: "dashboard_board",
    path: "/dashboard/workbench",
    title: "Bảng điều khiển",
    requiresAuth: true,
    icon: "icon-park-outline:dashboard",
    menuType: "page",
    componentPath: "/admin/dashboard/workbench/index.vue",
    id: 101,
    pid: 1,
  },
  {
    name: "dashboard_sales",
    path: "/dashboard/sales",
    title: "Bán hàng tại quầy",
    requiresAuth: true,
    icon: "icon-park-outline:shopping-cart",
    menuType: "page",
    componentPath: "/admin/dashboard/sales/index.vue",
    id: 102,
    pid: 1,
  },

  // Thống kê
  {
    name: "monitor",
    path: "/monitor",
    title: "Thống kê",
    requiresAuth: true,
    icon: "icon-park-outline:alignment-bottom-center", // thống kê
    menuType: "dir",
    componentPath: null,
    id: 2,
    pid: null,
  },
  {
    name: "monitor_stats",
    path: "/monitor/stats",
    title: "Thống kê",
    requiresAuth: true,
    icon: "icon-park-outline:analysis",
    menuType: "page",
    componentPath: "/admin/dashboard/monitor/index.vue",
    id: 201,
    pid: 2,
  },

  // Quản lý sản phẩm
  {
    name: "products",
    path: "/products",
    title: "Quản lý sản phẩm",
    requiresAuth: true,
    icon: "icon-park-outline:box",
    menuType: "dir",
    componentPath: null,
    id: 3,
    pid: null,
  },
  {
    name: "products_list",
    path: "/products/list",
    title: "Danh sách sản phẩm",
    requiresAuth: true,
    icon: "icon-park-outline:list",
    menuType: "page",
    componentPath: "/admin/products/list/index.vue",
    id: 301,
    pid: 3,
  },
  {
    name: "products_variant",
    path: "/products/variant",
    title: "Biến thể sản phẩm",
    requiresAuth: true,
    icon: "icon-park-outline:nine-points-connected",
    menuType: "page",
    componentPath: "/admin/products/variant/index.vue",
    id: 302,
    pid: 3,
  },
  {
    name: "products_attribute",
    path: "/products/attribute",
    title: "Thuộc tính",
    requiresAuth: true,
    icon: "icon-park-outline:setting",
    menuType: "dir",
    componentPath: null,
    id: 303,
    pid: 3,
  },
  {
    name: "products_brand",
    path: "/products/attribute/brand",
    title: "Thương hiệu",
    requiresAuth: true,
    icon: "carbon:carbon-ui-builder",
    menuType: "page",
    componentPath: "/admin/products/attribute/brand/index.vue",
    id: 30301,
    pid: 303,
  },
  {
    name: "products_company",
    path: "/products/attribute/company",
    title: "Hãng",
    requiresAuth: true,
    icon: "carbon:carbon-for-ibm-dotcom",
    menuType: "page",
    componentPath: "/admin/products/attribute/company/index.vue",
    id: 30302,
    pid: 303,
  },
  {
    name: "products_cpu",
    path: "/products/attribute/cpu",
    title: "CPU",
    requiresAuth: true,
    icon: "icon-park-outline:cpu",
    menuType: "page",
    componentPath: "/admin/products/attribute/cpu/index.vue",
    id: 30303,
    pid: 303,
  },
  {
    name: "products_gpu",
    path: "/products/attribute/gpu",
    title: "GPU",
    requiresAuth: true,
    icon: "icon-park-outline:full-screen-play",
    menuType: "page",
    componentPath: "/admin/products/attribute/gpu/index.vue",
    id: 30304,
    pid: 303,
  },
  {
    name: "products_battery",
    path: "/products/attribute/battery",
    title: "Pin",
    requiresAuth: true,
    icon: "carbon:battery-half",
    menuType: "page",
    componentPath: "/admin/products/attribute/battery/index.vue",
    id: 30305,
    pid: 303,
  },
  {
    name: "products_screen",
    path: "/products/attribute/screen",
    title: "Màn hình",
    requiresAuth: true,
    icon: "icon-park-outline:monitor",
    menuType: "page",
    componentPath: "/admin/products/attribute/screen/index.vue",
    id: 30306,
    pid: 303,
  },
  {
    name: "products_material",
    path: "/products/attribute/material",
    title: "Chất liệu",
    requiresAuth: true,
    icon: "icon-park-outline:loading",
    menuType: "page",
    componentPath: "/admin/products/attribute/material/index.vue",
    id: 30307,
    pid: 303,
  },
  {
    name: "products_color",
    path: "/products/attribute/color",
    title: "Màu sắc",
    requiresAuth: true,
    icon: "icon-park-outline:platte",
    menuType: "page",
    componentPath: "/admin/products/attribute/color/index.vue",
    id: 30308,
    pid: 303,
  },
  {
    name: "products_ram",
    path: "/products/attribute/ram",
    title: "RAM",
    requiresAuth: true,
    icon: "icon-park-outline:memory",
    menuType: "page",
    componentPath: "/admin/products/attribute/ram/index.vue",
    id: 30309,
    pid: 303,
  },
  {
    name: "products_storage",
    path: "/products/attribute/storage",
    title: "Ổ cứng",
    requiresAuth: true,
    icon: "icon-park-outline:hdd",
    menuType: "page",
    componentPath: "/admin/products/attribute/storage/index.vue",
    id: 30310,
    pid: 303,
  },

  // Quản lý đơn hàng
  {
    name: "orders",
    path: "/orders",
    title: "Quản lý đơn hàng",
    requiresAuth: true,
    icon: "icon-park-outline:shopping-bag",
    menuType: "dir",
    componentPath: null,
    id: 4,
    pid: null,
  },
  {
    name: "orders_list",
    path: "/orders/list",
    title: "Danh sách đơn hàng",
    requiresAuth: true,
    icon: "icon-park-outline:list",
    menuType: "page",
    componentPath: "/admin/orders/list/index.vue",
    id: 401,
    pid: 4,
  },

  // Quản lý người dùng
  {
    name: "users",
    path: "/users",
    title: "Quản lý người dùng",
    requiresAuth: true,
    icon: "icon-park-outline:user-to-user-transmission",
    menuType: "dir",
    componentPath: null,
    id: 5,
    pid: null,
  },
  {
    name: "users_staff",
    path: "/users/staff",
    title: "Nhân viên",
    requiresAuth: true,
    icon: "icon-park-outline:address-book",
    menuType: "page",
    componentPath: "/admin/users/staff/index.vue",
    id: 501,
    pid: 5,
  },
  {
    name: "users_customer",
    path: "/users/customer",
    title: "Khách hàng",
    requiresAuth: true,
    icon: "icon-park-outline:user-positioning",
    menuType: "page",
    componentPath: "/admin/users/customer/index.vue",
    id: 502,
    pid: 5,
  },

  // Quản lý giảm giá
  {
    name: "discounts",
    path: "/discounts",
    title: "Quản lý giảm giá",
    requiresAuth: true,
    icon: "icon-park-outline:coupon",
    menuType: "dir",
    componentPath: null,
    id: 6,
    pid: null,
  },
  {
    name: "discounts_campaign",
    path: "/discounts/campaign",
    title: "Đợt giảm giá",
    requiresAuth: true,
    icon: "icon-park-outline:calendar",
    menuType: "page",
    componentPath: "/admin/discounts/campaign/index.vue",
    id: 601,
    pid: 6,
  },
  {
    name: "discounts_coupon",
    path: "/discounts/coupon",
    title: "Phiếu giảm giá",
    requiresAuth: true,
    icon: "icon-park-outline:ticket",
    menuType: "page",
    componentPath: "/admin/discounts/coupon/index.vue",
    id: 602,
    pid: 6,
  },

  // Hỗ trợ khách hàng
  {
    name: "support",
    path: "/support",
    title: "Hỗ trợ khách hàng",
    requiresAuth: true,
    icon: "carbon:user-service-desk",
    menuType: "dir",
    componentPath: null,
    id: 7,
    pid: null,
  },
  {
    name: "support_chat",
    path: "/support/chat",
    title: "Chat thường",
    requiresAuth: true,
    icon: "icon-park-outline:communication",
    menuType: "page",
    componentPath: "/admin/support/chat/index.vue",
    id: 701,
    pid: 7,
  },
];
