export const staticRoutes: AppRoute.RowRoute[] = [
  // Bàn làm việc
  {
    name: 'dashboard_sales',
    path: '/dashboard/sales',
    title: 'Bán hàng tại quầy',
    requiresAuth: true,
    roles: ['QUAN_LY', 'NHAN_VIEN'],
    icon: 'icon-park-outline:shopping-cart',
    menuType: 'page',
    componentPath: '/admin/banhang/index.vue',
    id: 1,
    pid: null,
  },

  {
    name: 'monitor_stats',
    path: '/monitor/stats',
    title: 'Thống kê',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    roles: ['QUAN_LY'],
    menuType: 'page',
    componentPath: '/admin/dashboard/monitor/index.vue',
    id: 2,
    pid: null,
  },

  // Quản lý sản phẩm
  {
    name: 'products',
    path: '/products',
    title: 'Quản lý sản phẩm',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:box',
    menuType: 'dir',
    componentPath: null,
    id: 3,
    pid: null,
  },
  {
    name: 'products_list',
    path: '/products/list',
    title: 'Danh sách sản phẩm',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:list',
    menuType: 'page',
    componentPath: '/admin/products/list/index.vue',
    id: 301,
    pid: 3,
  },
  {
    name: 'products_add',
    path: '/products/add/:id?',
    title: 'Thêm sản phẩm',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    hide: true,
    icon: 'icon-park-outline:ad-product',
    menuType: 'page',
    componentPath: '/admin/products/list/component/ADAddProduct.vue',
    id: 310,
    pid: 3,
  },
  {
    name: 'products_variant',
    path: '/products/variant',
    title: 'Biến thể sản phẩm',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:nine-points-connected',
    menuType: 'page',
    componentPath: '/admin/products/variant/index.vue',
    id: 302,
    pid: 3,
  },
  {
    name: 'products_attribute',
    path: '/products/attribute',
    title: 'Thuộc tính',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:setting',
    menuType: 'dir',
    componentPath: null,
    id: 303,
    pid: 3,
  },
  {
    name: 'products_brand',
    path: '/products/attribute/brand',
    title: 'Thương hiệu',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'carbon:carbon-ui-builder',
    menuType: 'page',
    componentPath: '/admin/products/attribute/brand/index.vue',
    id: 30301,
    pid: 303,
  },
  {
    name: 'products_company',
    path: '/products/attribute/company',
    title: 'Hệ điều hành',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'carbon:carbon-for-ibm-dotcom',
    menuType: 'page',
    componentPath: '/admin/products/attribute/operating/index.vue',
    id: 30302,
    pid: 303,
  },
  {
    name: 'products_cpu',
    path: '/products/attribute/cpu',
    title: 'CPU',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:cpu',
    menuType: 'page',
    componentPath: '/admin/products/attribute/cpu/index.vue',
    id: 30303,
    pid: 303,
  },
  {
    name: 'products_gpu',
    path: '/products/attribute/gpu',
    title: 'GPU',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:full-screen-play',
    menuType: 'page',
    componentPath: '/admin/products/attribute/gpu/index.vue',
    id: 30304,
    pid: 303,
  },
  {
    name: 'products_battery',
    path: '/products/attribute/battery',
    title: 'Pin',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'carbon:battery-half',
    menuType: 'page',
    componentPath: '/admin/products/attribute/battery/index.vue',
    id: 30305,
    pid: 303,
  },
  {
    name: 'products_screen',
    path: '/products/attribute/screen',
    title: 'Màn hình',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:monitor',
    menuType: 'page',
    componentPath: '/admin/products/attribute/screen/index.vue',
    id: 30306,
    pid: 303,
  },
  {
    name: 'products_material',
    path: '/products/attribute/material',
    title: 'Chất liệu',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:loading',
    menuType: 'page',
    componentPath: '/admin/products/attribute/material/index.vue',
    id: 30307,
    pid: 303,
  },
  {
    name: 'products_color',
    path: '/products/attribute/color',
    title: 'Màu sắc',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:platte',
    menuType: 'page',
    componentPath: '/admin/products/attribute/color/index.vue',
    id: 30308,
    pid: 303,
  },
  {
    name: 'products_ram',
    path: '/products/attribute/ram',
    title: 'RAM',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:memory',
    menuType: 'page',
    componentPath: '/admin/products/attribute/ram/index.vue',
    id: 30309,
    pid: 303,
  },
  {
    name: 'products_storage',
    path: '/products/attribute/storage',
    title: 'Ổ cứng',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:hdd',
    menuType: 'page',
    componentPath: '/admin/products/attribute/harddrive/index.vue',
    id: 30310,
    pid: 303,
  },
  {
    name: 'orders_list',
    path: '/orders/list',
    title: 'Danh sách đơn hàng',
    requiresAuth: true,
    roles: ['QUAN_LY', 'NHAN_VIEN'],
    icon: 'icon-park-outline:list',
    menuType: 'page',
    componentPath: '/admin/hoadon/index.vue',
    id: 4,
    pid: null,
  },
  {
    name: 'orders_detail',
    path: '/orders/detail/:id', // QUAN TRỌNG: Đây là URL sẽ dùng

    roles: ['QUAN_LY', 'NHAN_VIEN'],
    title: 'Chi tiết đơn hàng',
    requiresAuth: true,
    hide: true,
    componentPath: '/admin/hoadon/HoaDonDetailAdmin.vue',

    id: 4,
    pid: 401,
  },

  // {
  //   name: 'invoice_list',
  //   path: '/invoice',
  //   title: 'Quản lý hoá đơn',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   menuType: 'page',
  //   componentPath: '/admin/invoice/invoiceList.vue',
  //   id: 8,
  //   pid: null,
  // },

  // {
  //   name: 'invoice_list_detail',
  //   path: '/invoice/detail/:id',
  //   title: 'Chi tiết hoá đơn',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   hide: true,
  //   menuType: 'page',
  //   componentPath: '/admin/invoice/invoiceDetail.vue',
  //   id: 801,
  //   pid: null,
  // },

  // Quản lý người dùng
  {
    name: 'users',
    path: '/users',
    title: 'Quản lý người dùng',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:user-to-user-transmission',
    menuType: 'dir',
    componentPath: null,
    id: 5,
    pid: null,
  },
  {
    name: 'users_staff',
    path: '/users/staff',
    title: 'Nhân viên',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:peoples', // Đổi icon cho khác khách hàng một chút
    menuType: 'page',
    componentPath: '/admin/users/staff/index.vue', // File index cho staff của bạn
    id: 505,
    pid: 5,
  },
  {
    name: 'users_staff_add',
    path: '/users/staff/add',
    title: 'Thêm nhân viên',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    hide: true, // Ẩn khỏi menu
    icon: 'icon-park-outline:user-plus',
    menuType: 'page',
    // Giả sử bạn đặt tên file form là StaffForm.vue, nếu khác hãy sửa lại nhé
    componentPath: '/admin/users/staff/StaffDetail.vue',
    id: 506,
    pid: 5,
  },
  {
    name: 'users_staff_edit',
    path: '/users/staff/edit/:id',
    title: 'Sửa nhân viên',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    hide: true, // Ẩn khỏi menu
    icon: 'icon-park-outline:user-edit',
    menuType: 'page',
    // Dùng chung form với trang thêm mới
    componentPath: '/admin/users/staff/StaffDetail.vue',
    id: 507,
    pid: 5,
  },
  {
    name: 'users_customer',
    path: '/users/customer',
    title: 'Khách hàng',
    requiresAuth: true,
    roles: ['QUAN_LY', 'NHAN_VIEN'],
    icon: 'icon-park-outline:user-positioning',
    menuType: 'page',
    componentPath: '/admin/users/customer/index.vue',
    id: 502,
    pid: 5,
  },
  {
    name: 'users_customer_add',
    path: '/users/customer/add',
    title: 'Thêm khách hàng',
    requiresAuth: true,
    hide: true, // Ẩn khỏi menu
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:user-plus',
    menuType: 'page',
    componentPath: '/admin/users/customer/CustomerForm.vue',
    id: 503,
    pid: 5, // Thay đổi pid từ 502 thành 5 (parent users)
  },
  {
    name: 'users_customer_edit',
    path: '/users/customer/edit/:id',
    title: 'Sửa khách hàng',
    requiresAuth: true,
    hide: true, // Ẩn khỏi menu
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:user-edit',
    menuType: 'page',
    componentPath: '/admin/users/customer/CustomerForm.vue',
    id: 504,
    pid: 5, // Thay đổi pid từ 502 thành 5 (parent users)
  },

  // Quản lý giảm giá
  {
    name: 'discounts',
    path: '/discounts',
    title: 'Quản lý giảm giá',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:coupon',
    menuType: 'dir',
    componentPath: null,
    id: 6,
    pid: null,
  },

  {
    name: 'discounts_voucher',
    path: '/discounts/voucher',
    title: 'Phiếu giảm giá',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:ticket',
    menuType: 'page',
    componentPath: '/admin/discounts/voucher/index.vue',
    id: 605,
    pid: 6,
  },

  {
    name: 'discounts_voucher_add',
    path: '/discounts/voucher/add',
    title: 'Thêm Phiếu giảm giá',
    requiresAuth: true,
    hide: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:add',
    menuType: 'page',
    componentPath: '/admin/discounts/voucher/AddEditVoucher.vue',
    id: 606,
    pid: 6,
  },

  {
    name: 'discounts_voucher_edit',
    path: '/discounts/voucher/edit/:id',
    title: 'Sửa Phiếu giảm giá',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    hide: true,
    icon: 'icon-park-outline:edit',
    menuType: 'page',
    componentPath: '/admin/discounts/voucher/AddEditVoucher.vue',
    id: 607,
    pid: 6,
  },

  {
    name: 'discounts_voucher_detail',
    path: '/discounts/voucher/detail/:id',
    title: 'Chi tiết Phiếu giảm giá',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    hide: true,
    icon: 'icon-park-outline:edit',
    menuType: 'page',
    componentPath: '/admin/discounts/voucher/AddEditVoucher.vue',
    id: 608,
    pid: 6,
  },

  {
    name: 'discounts_campaign',
    path: '/discounts/campaign',
    title: 'Đợt giảm giá',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:calendar',
    menuType: 'page',
    componentPath: '/admin/discounts/promotion/index.vue',
    id: 601,
    pid: 6,
  },
  {
    name: 'discounts_campaign_add',
    path: '/discounts/campaign/add',
    title: 'Thêm đợt giảm giá',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    hide: true,
    icon: 'icon-park-outline:add',
    menuType: 'page',
    componentPath: '/admin/discounts/promotion/pages/Add.vue',
    id: 603,
    pid: 6,
  },
  {
    name: 'discounts_campaign_edit',
    path: '/discounts/campaign/edit/:id',
    title: 'Sửa đợt giảm giá',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    hide: true,
    icon: 'icon-park-outline:edit',
    menuType: 'page',
    componentPath: '/admin/discounts/promotion/pages/Update.vue',
    id: 604,
    pid: 6,
  },

  {
    name: 'work_schedule',
    path: '/work-schedule',
    title: 'Quản lý lịch làm việc',
    requiresAuth: true,
    roles: ['QUAN_LY', 'NHAN_VIEN'],
    icon: 'icon-park-outline:calendar',
    menuType: 'dir',
    componentPath: null,
    id: 65, // ID nằm giữa 6 (Giảm giá) và 7 (Hỗ trợ)
    pid: null,
  },
  {
    name: 'shift_manager',
    path: '/work-schedule/shifts',
    title: 'Quản lý Ca làm việc',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:time',
    menuType: 'page',
    // Trỏ đến file: src/views/work-schedule/ShiftManager.vue
    componentPath: '/admin/shiftmanager/ShiftManager.vue',
    id: 651,
    pid: 65,
  },
  {
    name: 'schedule_assign',
    path: '/work-schedule/assign',
    title: 'Xếp lịch nhân viên',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:plan',
    menuType: 'page',
    // Trỏ đến file: src/views/work-schedule/WorkSchedule.vue
    componentPath: '/admin/shiftmanager/WorkSchedule.vue',
    id: 652,
    pid: 65,
  },
  {
    name: 'shift_history',
    path: '/work-schedule/history',
    title: 'Lịch sử hoạt động',
    requiresAuth: true,
    roles: ['QUAN_LY'], // Chỉ cho phép Quản lý xem toàn bộ lịch sử cửa hàng
    icon: 'icon-park-outline:history', // Thêm icon quyển sách lịch sử
    menuType: 'page',
    // Trỏ đến file ShiftHistory.vue bạn vừa tạo lúc nãy
    componentPath: '/admin/shiftmanager/ShiftHistory.vue',
    id: 655, // ID mới, tránh trùng lặp
    pid: 65, // Thuộc nhóm "Quản lý lịch làm việc"
  },
  {
    name: 'schedule_view',
    path: '/work-schedule/view',
    title: 'Lịch làm việc',
    requiresAuth: true,
    roles: ['NHAN_VIEN'],
    icon: 'icon-park-outline:calendar',
    menuType: 'page',
    // QUAN TRỌNG: Đường dẫn này phải khớp với nơi bạn lưu file .vue mới
    componentPath: '/admin/shiftmanager/StaffScheduleView.vue',
    id: 654,
    pid: 65,
  },
  {
    name: 'shift_handover',
    path: '/work-schedule/handover',
    title: 'Giao ca & Kết toán',
    requiresAuth: true,
    roles: ['NHAN_VIEN'],
    icon: 'icon-park-outline:finance',
    menuType: 'page',
    // Trỏ đến file: src/views/work-schedule/Handover.vue
    componentPath: '/admin/shiftmanager/ShiftHandover.vue',
    id: 653,
    pid: 65,
  },

  // Hỗ trợ khách hàng
  {
    name: 'support',
    path: '/support',
    title: 'Hỗ trợ khách hàng',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'carbon:user-service-desk',
    menuType: 'dir',
    componentPath: null,
    id: 7,
    pid: null,
  },
  {
    name: 'support_chat',
    path: '/support/chat',
    title: 'Chat thường',
    requiresAuth: true,
    roles: ['QUAN_LY'],
    icon: 'icon-park-outline:communication',
    menuType: 'page',
    componentPath: '/admin/support/Chat.vue',
    id: 701,
    pid: 7,
  },
]
